"""
modules/script_generator.py
Generates a personalised, ready-to-run Python preprocessing script
based on what Vektor found in the dataset.
"""


def generate_preprocessing_script(df, meta: dict) -> str:
    """
    Returns a Python script string tailored to this exact dataset.
    Every step uses real column names — not a generic template.
    """
    anal_num   = meta.get("anal_num", [])
    cat_cols   = meta.get("cat_cols", [])
    id_cols    = meta.get("id_cols", [])
    const_cols = meta.get("const_cols", [])
    high_null  = meta.get("high_null", [])
    high_skew  = meta.get("high_skew", [])
    n_rows     = meta.get("n_rows", len(df))
    n_cols     = meta.get("n_cols", len(df.columns))
    problem_type = meta.get("problem_type", "Unknown")

    # Low-cardinality categoricals safe for one-hot encoding
    low_card  = [c for c in cat_cols if 2 <= df[c].nunique() <= 15
                 and c not in high_null]
    high_card = [c for c in cat_cols if df[c].nunique() > 15
                 and c not in high_null]

    # Numeric cols that need imputation (not high_null, not const, not id)
    num_impute = [c for c in anal_num
                  if df[c].isnull().sum() > 0 and c not in high_null]
    cat_impute = [c for c in cat_cols
                  if df[c].isnull().sum() > 0 and c not in high_null]

    # Numeric cols to scale (exclude skewed — those get log1p first)
    scale_cols = [c for c in anal_num if c not in high_null]

    # Drop cols
    drop_cols = list(set(id_cols + const_cols))

    lines = []

    # ── Header ────────────────────────────────────────────────────────────────
    lines += [
        '"""',
        f'Vektor — Auto-Generated Preprocessing Script',
        f'Dataset: {n_rows} rows × {n_cols} columns',
        f'Problem type: {problem_type}',
        f'',
        f'Generated by Vektor. Edit as needed before training.',
        '"""',
        '',
        'import pandas as pd',
        'import numpy as np',
        'from sklearn.preprocessing import StandardScaler, LabelEncoder',
        'from sklearn.model_selection import train_test_split',
        '',
        '',
        '# ── 1. LOAD DATA ──────────────────────────────────────────────────────',
        "df = pd.read_csv('your_dataset.csv')  # ← replace with your file path",
        "print(f'Loaded: {df.shape[0]} rows × {df.shape[1]} columns')",
        '',
    ]

    # ── 2. Drop useless columns ───────────────────────────────────────────────
    lines += ['# ── 2. DROP ID & CONSTANT COLUMNS ────────────────────────────────────']
    if drop_cols:
        lines += [
            f'drop_cols = {drop_cols}',
            "drop_cols = [c for c in drop_cols if c in df.columns]  # safety check",
            'df = df.drop(columns=drop_cols)',
            f"print(f'Dropped {len(drop_cols)} useless column(s): {drop_cols}')",
        ]
    else:
        lines += ['# No ID or constant columns detected — nothing to drop']
    lines.append('')

    # ── 3. Drop high-null columns ─────────────────────────────────────────────
    lines += ['# ── 3. DROP HIGH-NULL COLUMNS (>30% missing) ─────────────────────────']
    if high_null:
        lines += [
            f'high_null_cols = {high_null}',
            'high_null_cols = [c for c in high_null_cols if c in df.columns]',
            'df = df.drop(columns=high_null_cols)',
            f"print(f'Dropped high-null columns: {high_null}')",
        ]
    else:
        lines += ['# No columns with >30% missing values detected']
    lines.append('')

    # ── 4. Remove duplicates ──────────────────────────────────────────────────
    lines += [
        '# ── 4. REMOVE DUPLICATE ROWS ─────────────────────────────────────────',
        'before = len(df)',
        'df = df.drop_duplicates()',
        "print(f'Removed {before - len(df)} duplicate row(s)')",
        '',
    ]

    # ── 5. Impute missing values ──────────────────────────────────────────────
    lines += ['# ── 5. IMPUTE MISSING VALUES ──────────────────────────────────────────']
    if num_impute:
        lines += [
            f'# Numeric columns — fill with median',
            f'num_impute_cols = {num_impute}',
            'for col in num_impute_cols:',
            '    if col in df.columns:',
            '        df[col] = df[col].fillna(df[col].median())',
        ]
    if cat_impute:
        lines += [
            f'# Categorical columns — fill with mode',
            f'cat_impute_cols = {cat_impute}',
            'for col in cat_impute_cols:',
            '    if col in df.columns:',
            '        df[col] = df[col].fillna(df[col].mode()[0])',
        ]
    if not num_impute and not cat_impute:
        lines += ['# No missing values detected — nothing to impute']
    lines.append('')

    # ── 6. Fix skewed distributions ───────────────────────────────────────────
    lines += ['# ── 6. FIX SKEWED DISTRIBUTIONS (log1p transform) ────────────────────']
    if high_skew:
        lines += [
            f'skewed_cols = {high_skew}',
            'for col in skewed_cols:',
            '    if col in df.columns:',
            '        # Shift to positive before log if needed',
            '        if df[col].min() <= 0:',
            '            df[col] = df[col] - df[col].min() + 1',
            '        df[col] = np.log1p(df[col])',
            f"print(f'Applied log1p to {len(high_skew)} skewed column(s)')",
        ]
    else:
        lines += ['# No highly skewed columns detected']
    lines.append('')

    # ── 7. Encode categoricals ────────────────────────────────────────────────
    lines += ['# ── 7. ENCODE CATEGORICAL COLUMNS ────────────────────────────────────']
    if low_card:
        lines += [
            f'# Low-cardinality — One-Hot Encoding',
            f'ohe_cols = {low_card}',
            'ohe_cols = [c for c in ohe_cols if c in df.columns]',
            'df = pd.get_dummies(df, columns=ohe_cols, drop_first=True)',
            f"print(f'One-hot encoded: {low_card}')",
        ]
    if high_card:
        lines += [
            f'# High-cardinality — Label Encoding (consider Target Encoding for better results)',
            f'hc_cols = {high_card}',
            'le = LabelEncoder()',
            'for col in hc_cols:',
            '    if col in df.columns:',
            '        df[col] = df[col].astype(str).fillna("__missing__")',
            '        df[col] = le.fit_transform(df[col])',
            f"print(f'Label encoded high-cardinality cols: {high_card}')",
        ]
    if not low_card and not high_card:
        lines += ['# No categorical columns to encode']
    lines.append('')

    # ── 8. Scale numeric features ─────────────────────────────────────────────
    lines += ['# ── 8. SCALE NUMERIC FEATURES ────────────────────────────────────────']
    if scale_cols:
        lines += [
            f'scale_cols = {scale_cols}',
            'scale_cols = [c for c in scale_cols if c in df.columns]',
            'scaler = StandardScaler()',
            'df[scale_cols] = scaler.fit_transform(df[scale_cols])',
            f"print(f'Scaled {len(scale_cols)} numeric column(s) with StandardScaler')",
        ]
    else:
        lines += ['# No numeric columns to scale']
    lines.append('')

    # ── 9. Train/test split ───────────────────────────────────────────────────
    lines += [
        '# ── 9. TRAIN / TEST SPLIT ────────────────────────────────────────────',
        "# ⚠ Replace 'your_target_column' with your actual target column name",
        "TARGET = 'your_target_column'",
        '',
        'if TARGET in df.columns:',
        '    X = df.drop(columns=[TARGET])',
        '    y = df[TARGET]',
        '    X_train, X_test, y_train, y_test = train_test_split(',
        '        X, y, test_size=0.2, random_state=42',
        '    )',
        "    print(f'Train: {X_train.shape}, Test: {X_test.shape}')",
        'else:',
        "    print(f'Target column not found. Set TARGET to your column name above.')",
        "    print(f'Available columns: {list(df.columns)}')",
        '',
    ]

    # ── 10. Final summary ─────────────────────────────────────────────────────
    lines += [
        '# ── 10. FINAL SUMMARY ────────────────────────────────────────────────',
        "print('\\n=== Preprocessing Complete ===')",
        "print(f'Final dataset shape: {df.shape}')",
        "print(f'Columns: {list(df.columns)}')",
        "print(f'Missing values remaining: {df.isnull().sum().sum()}')",
    ]

    return '\n'.join(lines)
